FirebaseExtended/firebase-arduino

firebase/firebase.ino
Usage:
```
AT+CWJAP=ssid,passwd
```
Only persist to eeprom if connected.
Fixes #3
=> firebase: add wifi commands

Firebase.cpp, Firebase.h, README.md, examples/FirebasePush_ESP8266/FirebasePush_ESP8266.ino
esp8266/Arduino added an http client in their libraries: https://github.com/esp8266/Arduino/pull/1081, let's switch to that :)
We should file separate issues and contribute PR for the current limitations.
- implicit and blocking connect (apparently lwip support non blocking connect and protected `connect()` could be exposed via a derived class).
- no support for `PUT` `DELETE` `PATCH` `UPDATE`.
- setter for certs/key but no impl.
Fixes #21 #19.
=> switch to ESP8266HTTPClient

Firebase.cpp, Firebase.h, README.md, examples/FirebasePush_ESP8266/FirebasePush_ESP8266.ino
- remove `FirebaseRoot` type
- remove global `Firebase` object
Fixes #26.
For those lacking context on the change, it's mostly a refactoring to simplify the main Firebase object creation and work around global initialization order.
I'd suggest to look at the example code as a guide for the review:
https://github.com/proppy/firebase-iot-button/blob/remove-global/examples/FirebasePush_ESP8266/FirebasePush_ESP8266.ino
/cc @leedenison @aliafshar @gguuss @beriberikix @tjohns
=> remove FirebaseRoot

Firebase.cpp, Firebase.h, examples/FirebasePush_ESP8266/FirebasePush_ESP8266.ino
As @mimming pointed out, `val(key)` is confusing because, in other fb lib it represents a client side operation to materialize a value from a synced cache, while our usage here is doing an active request.
Let's call that `get()`
=> Firebase: replace val by get

examples/FirebaseStream_ESP8266/FirebaseStream_ESP8266.ino
Update the streaming example to display bitcoin price.
- [Feather Huzzah](https://www.adafruit.com/products/2821)
- [Feather OLED wing](https://www.adafruit.com/products/2900) (optional, also stream to Serial)
- https://github.com/adafruit/Adafruit-GFX-Library
- https://github.com/adafruit/Adafruit_SSD1306
/cc @JoseAlcerreca @gguuss
Based on #34.
=> bitcoin ticker

Firebase.cpp, Firebase.h
=> Added remove() method.

Firebase.cpp, Firebase.h
=> firebase: add set

Firebase.cpp, Firebase.h, examples/FirebasePush_ESP8266/FirebasePush_ESP8266.ino, examples/FirebaseStream_ESP8266/FirebaseStream_ESP8266.ino
As discussed in issue #41 
Refactored to provide result and not depend on class state for error reporting, conform to Google C++ style.
Also broke FirebaseEventStream out from Firebase. When this is connected I believe any other calls (push,fetch,etc..) to the class would break it. For that reason it really seems like this should be its own focused class. Or you need large comments explaining this gotcha.
=> Refactored Firebase library

Firebase.cpp, Firebase.h
=> firebase: restore set method

Firebase.cpp, Firebase.h, examples/FirebaseStream_ESP8266/FirebaseStream_ESP8266.ino
See #38
Only add json decoding in the streaming sample for now, while we discuss proper integration in #43.
/cc @gguuss @ed7coyne
=> example/stream: use ArduinoJson

examples/FirebaseStream_ESP8266/FirebaseStream_ESP8266.ino
So my previous fix only fixed the first result in the stream. All of the others are of a different format. However if we ask for the /last value directly all results look the same.
Didn't see this before because the job updating the bitcoin database was down and it wasn't seeing any updates but that is fixed now.
=> Fix streaming parsing

.travis.yml
This add travis jobs for the following combination of arduino and esp8266 cores:
| Arduino | ESP8266 |
| --- | --- |
| 1.6.8 | 2.1.0 |
| 1.6.8 | 2.2.0-rc1 |
| nightly | master |
This will hopefully helps to to catch future breakage.
Fixes #56.
=> add travis for arduino/esp8266

examples/FirebasePush_ESP8266/FirebasePush_ESP8266.ino, src/Firebase.cpp, src/Firebase.h
Change firebase construction to be saner and avoid calling the copy constructor.
We should probably also add `begin()`.
This should make the new esp-travis integration merged in #88 pass for all arduino/esp combination.
=> firebase: fix ctor

examples/FirebaseRoom_ESP8266/FirebaseRoom_ESP8266.ino, examples/FirebaseRoom_ESP8266/README.md
- add tutorial in README.md
- prepopulate data on `setup()`
=> add FirebaseRoom README

examples/FirebaseDemo_ESP8266/FirebaseDemo_ESP8266.ino, examples/FirebaseRoom_ESP8266/FirebaseRoom_ESP8266.ino, examples/FirebaseStream_ESP8266/FirebaseStream_ESP8266.ino, src/FirebaseArduino.cpp, src/FirebaseArduino.h, src/FirebaseObject.cpp, src/FirebaseObject.h, test/FirebaseArduino_test.cpp
- remove cast operator
- remove indexing method
- accept a subpath
Fixes #133 #109
=> FirebaseObject: simplify API

examples/FirebaseDemo_ESP8266/README.md, examples/FirebaseRoom_ESP8266/README.md, examples/FirebaseStream_ESP8266/README.md
=> examples: add README for Demo and Stream example.

examples/FirebaseDemo_ESP8266/README.md, examples/FirebaseRoom_ESP8266/README.md, examples/FirebaseStream_ESP8266/README.md
=> examples: update README

src/FirebaseObject.cpp, test/FirebaseArduino_test.cpp
fix decoding of integer when using `getFloat` and decoding of float when using `getInt`
=> firebaseobject: fix number decoding

examples/FirebaseRoom_ESP8266/README.md
OS X users needs to install Silicon Labs driver, otherwise serial port won't be correctly displayed at 'Select the serial port Port > /dev/tty...' step.
=> Mention installing Sillicon Labs driver for OS X

examples/FirebaseDemo_ESP8266/README.md, examples/FirebaseNeoPixel_ESP8266/README.md, examples/FirebaseStream_ESP8266/README.md
=> examples: update firebase console instructions

src/FirebaseHttpClient_Esp8266.cpp
Was getting the following warnings:
/Users/foo/Documents/Arduino/libraries/firebase-arduino-master/src/FirebaseHttpClient_Esp8266.cpp: In member function 'virtual void FirebaseHttpClientEsp8266::begin(const string&, const string&)':
/Users/foo/Documents/Arduino/libraries/firebase-arduino-master/src/FirebaseHttpClient_Esp8266.cpp:31:86: warning: 'bool HTTPClient::begin(String, uint16_t, String, bool, String)' is deprecated (declared at /Users/foo/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.h:141) [-Wdeprecated-declarations]
http_.begin(host.c_str(), kFirebasePort, path.c_str(), true, kFirebaseFingerprint);
Followed the recommendation at https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266HTTPClient/src/ESP8266HTTPCl …
=> Fixing deprecation warning on HttpClient begin

src/thing/Portal.cpp, src/thing/Portal.h, src/thing/Transcriber.cpp
Use the ESP network module to allow the user to scan for networks.
=> Added network scanning to config portal.

src/Portal.h, src/Thing.h, src/Transcriber.h, src/thing/Portal.cpp, src/thing/WiFiManager.cpp, src/thing/WiFiManager.h
This is working but there are some kinks that still need to be worked out with the whole system. I want to be able to cleanly keep the portal accessible while the user tests wifi settings. Currently this works if the network they wish to connect to and the Firething's network happen to be on the same channel. We should have a better story for what happens when they aren't. 
This is the last major piece of the Firething, all we need to do now is store the Config in flash when updated. I will implement something for that next and do a lot more testing and tweaking.
=> Initial implementation of WiFiManager

src/thing/Config.cpp, src/thing/Config.h, src/thing/FireThing.cpp, src/thing/FireThing.h, src/thing/Portal.cpp
Fixed bug where the webserver would close its connection while serving the config. The fix uses more memory due to extra copy but deeper debugging is required to determine whether the bug that is closing the connection is in ArduinoJson or in ESP8266WebServer's client object.
Also cleaned up interface for serialization by making it a class.
=> Clean up api for serialization, fix bug with config fetching from webserver.

src/FirebaseHttpClient.h
I noticed some weird crashes when trying to connect to my Firebase Database through firebase-arduino starting about yesterday. It seems that perhaps the certificate fingerprint has changed. Please independently verify my fix.
=> The SSL signature for Firebase seems to have changed

src/Firebase.cpp
I fixed the comment above `FirebaseRemove::FirebaseRemove`.  You probably don't need the comment, but since it's there, it should be right :)
=> Fixed a code comment

src/FirebaseHttpClient_Esp8266.cpp
=> FirebaseHttpClient: add forceReuse

src/Firebase.cpp, src/FirebaseArduino.cpp, src/FirebaseArduino.h, src/FirebaseHttpClient.h
With this change non-streaming operation will stop the stream and
reuse the underlying http client.
Call FirebaseArduino::stream again in order to reuse the stream.
This is similar to what @ed7coyne did in the `contrib/modem`
/cc @salqadri @kotl
Fixes: #48 #266
=> FirebaseArduino: allow mixing stream and non-stream commands

contrib/src/modem/command.h, contrib/src/modem/db/DatabaseProtocol.cpp, contrib/src/modem/db/DatabaseProtocol.h, contrib/src/modem/db/begin-command.cpp, contrib/src/modem/db/commands.h, contrib/src/modem/db/get-command.cpp, contrib/src/modem/db/push-command.cpp, contrib/src/modem/db/remove-command.cpp, contrib/src/modem/db/set-command.cpp, contrib/src/modem/db/stream-command.cpp, contrib/test/mock-firebase.h, contrib/test/modem/Makefile, contrib/test/modem/begin-command_test.cpp, contrib/test/modem/get-command_test.cpp, contrib/test/modem/push-command_test.cpp, contrib/test/modem/remove-command_test.cpp, contrib/test/modem/serial-transceiver_test.cpp, contrib/test/modem/set-command_test.cpp, contrib/test/modem/stream-command_test.cpp, src/Firebase.cpp, src/Firebase.h, src/FirebaseArduino.cpp, src/FirebaseArduino.h, src/FirebaseHttpClient.h
- This refactoring is fully compatible with previous FirebaseArduino.h interface and will use same or less amount of RAM if used in one-way mode (stream-only or get/set only).
- From now on, you won't need two instances of FirebaseArduino in order to be able to stream and change values at the same time: second https connection will be created dynamically and work while you are using stream mode. Bi-directional operation does require almost twice as much RAM, leaving only about 10k left for vanilla sample in ESP8266. You will also need to use ESP8266 Arduino core [2.4.1](https://github.com/esp8266/Arduino/tree/2.4.1) at the very least (that's when bi-directional support became possible due to fixes in https context). 
- Internal classes have been refactored into 2 to simplify development …
=> Add bi-directional (stream + get/set) support and refactoring of the internal classes 

contrib/test/FirebaseArduino_test.cpp, src/FirebaseObject.cpp
PR for #390 
* Reset the `_error` property on each getter call
* Added corresponding tests
* Fixed the existing float test (was comparing int, test was failing with a decimal).
=> [FirebaseObject] Error message is never reset #390

src/Firebase.cpp
I fix this issue
https://github.com/FirebaseExtended/firebase-arduino/issues/388
=> Fix issue #388 ESP8266 fails to reconnect to FIREBASE #388
