FirebaseExtended/firebase-arduino

libraries/Firebase/Firebase.cpp
libraries/Firebase/Firebase.h
libraries/Firebase/examples/FirebasePush_ESP8266/FirebasePush_ESP8266.ino

Untested, staging for early review.

libraries: add wip Firebase client library

---

Firebase.cpp
Firebase.h
examples/FirebaseStream_ESP8266/FirebaseStream_ESP8266.ino

Rebased on #31.
Fixes #20.
/cc @JoseAlcerreca

 add streaming method and examples

---

Firebase.cpp
Firebase.h
examples/FirebasePush_ESP8266/FirebasePush_ESP8266.ino
examples/FirebaseStream_ESP8266/FirebaseStream_ESP8266.ino

Fixes #33 
/cc @JoseAlcerreca @gguuss

remove child method

---

examples/FirebaseStream_ESP8266/FirebaseStream_ESP8266.ino

The json object now has multiple values in data{}. Changing the code to pull the "last" value.

Fix parsing of returned json object.

---

.travis.yml
examples/FirebaseDemo_ESP8266/FirebaseDemo_ESP8266.ino

/cc @gguuss @beriberikix @aliafshar 
Fixes #99

examples: rename push into a comprehensive demo

---

.travis.yml

- use ${VAR} everywhere
- use wget everywhere
- use unzip -q everywhere
- use the same library install procedure that @ed7coyne introduced for SoftwareSerial

travis: clean up

---

src/FirebaseArduino.h
src/FirebaseObject.h

FIREBASE_JSONBUFFER_SIZE cleanup

---

README.md

I switched http://firebase-arduino.readthedocs.io/en/latest/ over to point to the main repo, adding the badge to the readme.

Added ReadTheDocs badge.

---

examples/FirebaseRoom_ESP8266/FirebaseRoom_ESP8266.ino

Switch to using const ints for room example

---

library.properties

Change library name and add description.

---

examples/FirebaseStream_ESP8266/FirebaseStream_ESP8266.ino

Changed to new API. Still needs a README.

Change FirebaseStream example to use new API.

---

src/FirebaseArduino.cpp
src/FirebaseArduino.h

This will conflict with your simplified API but once that is in I will merge.

Support both string types in FirebaseArduino.h

---

README.md

README: add versioning disclaimer, link to samples

---

examples/FirebaseDemo_ESP8266/FirebaseDemo_ESP8266.ino
examples/FirebaseRoom_ESP8266/FirebaseRoom_ESP8266.ino
src/FirebaseArduino.cpp
src/FirebaseArduino.h

FirebaseArduino: add typed push and set variant

---

examples/FirebaseStream_ESP8266/FirebaseStream_ESP8266.ino

examples/FirebaseStream: stream data is stringified

---

examples/FirebaseRoom_ESP8266/FirebaseRoom_ESP8266.ino

examples/FirebaseRoom: add delay

---

examples/FirebaseDemo_ESP8266/FirebaseDemo_ESP8266.ino

Seems like we should handle error for all cases. Especially to set a good example.

Add error handling to FirebaseDemo

---

src/FirebaseArduino.cpp

Fix pushString() always write true

---

src/FirebaseHttpClient.h

FirebaseHttpClient: update firebaseio fingerprint

---

src/FirebaseHttpClient.h

The fingerprint changed on 2 Aug 2018.
This is the new fingerprint

Updating firebase fingerprint

---

src/FirebaseHttpClient.h

SSL fingerprint update 2020/02

SSL Fingerprint Update
